version: '3.8'

networks:
  gitlabnet:
    driver: bridge

services:

  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    hostname: ${HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
    ports:
      - 80:80
      - 10022:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
